
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  23/10/2012 10:10:34
 * Compiled by: UNODCAD\siljak
 * Source: C:\dev\GitHub\jsPasswordManager\src\helloWorld.coffee      
 * -------------------------------------------------------------------------*/


var TestClass;

console.log("Hello world!");

console.log("CoffeeScript works");

TestClass = (function() {
  var privateMethod;

  function TestClass() {}

  privateMethod = function() {};

  TestClass.prototype.publicMethod = function() {};

  return TestClass;

})();
